# Run this as: make migration name=InitialCreate
migration:
	dotnet ef migrations add $(name) --project lib/Whisprr.Infrastructure --startup-project services/Whisprr.Api -o Persistence/Migrations

update:
	dotnet ef database update --project lib/Whisprr.Infrastructure --startup-project services/Whisprr.Api