// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Whisprr.Infrastructure.Persistence;

#nullable disable

namespace Whisprr.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "sentiment", new[] { "negative", "neutral", "positive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_progress_status", new[] { "processing", "success", "failed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Whisprr.Entities.Models.SocialInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneratedFromTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sentiment")
                        .HasColumnType("sentiment");

                    b.Property<Guid>("SourcePlatformId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedFromTaskId");

                    b.HasIndex("SourcePlatformId");

                    b.ToTable("SocialInfos");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SocialTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialTopics");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SocialTopicListeningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SocialTopicId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourcePlatformId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("task_progress_status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SocialTopicId");

                    b.HasIndex("SourcePlatformId");

                    b.ToTable("SocialTopicListeningTask");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SourcePlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourcePlatforms");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SocialInfo", b =>
                {
                    b.HasOne("Whisprr.Entities.Models.SocialTopicListeningTask", "GeneratedFromTask")
                        .WithMany("GeneratedSocialInfos")
                        .HasForeignKey("GeneratedFromTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whisprr.Entities.Models.SourcePlatform", "SourcePlatform")
                        .WithMany("SocialInfos")
                        .HasForeignKey("SourcePlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedFromTask");

                    b.Navigation("SourcePlatform");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SocialTopicListeningTask", b =>
                {
                    b.HasOne("Whisprr.Entities.Models.SocialTopic", "SocialTopic")
                        .WithMany("SocialTopicListeningTask")
                        .HasForeignKey("SocialTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Whisprr.Entities.Models.SourcePlatform", "SourcePlatform")
                        .WithMany("SocialTopicListeningTasks")
                        .HasForeignKey("SourcePlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialTopic");

                    b.Navigation("SourcePlatform");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SocialTopic", b =>
                {
                    b.Navigation("SocialTopicListeningTask");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SocialTopicListeningTask", b =>
                {
                    b.Navigation("GeneratedSocialInfos");
                });

            modelBuilder.Entity("Whisprr.Entities.Models.SourcePlatform", b =>
                {
                    b.Navigation("SocialInfos");

                    b.Navigation("SocialTopicListeningTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
